import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import Editor from '@monaco-editor/react';
import {Folder,FileCode2,GitBranch,Search,Play,Save,RefreshCw,Plus,Trash2,Terminal,CheckCircle2,Download,Upload,Copy,Command,Settings,FilePlus,FolderPlus,History,PanelLeft,BookOpen,Keyboard,Sun,Moon,Maximize2} from 'lucide-react';
import './styles.css';
const LANGUAGES=[['javascript','JavaScript'],['typescript','TypeScript'],['html','HTML'],['css','CSS'],['json','JSON'],['python','Python'],['java','Java'],['c','C'],['cpp','C++'],['csharp','C#'],['go','Go'],['rust','Rust'],['php','PHP'],['ruby','Ruby'],['swift','Swift'],['kotlin','Kotlin'],['dart','Dart'],['sql','SQL'],['shell','Shell'],['markdown','Markdown'],['yaml','YAML'],['xml','XML'],['dockerfile','Dockerfile'],['graphql','GraphQL'],['lua','Lua'],['perl','Perl'],['r','R'],['powershell','PowerShell'],['plaintext','Plain Text']];
const DEFAULT_FILES={'main.js':'function hello() {\n  console.log("Hello from FluxIDE!");\n}\n\nhello();','README.md':'# FluxIDE\n\nA web-first developer workspace.\n\nTry the command palette with Ctrl+K.','package.json':'{\n  "name": "my-project",\n  "version": "1.0.0",\n  "scripts": {"start": "node main.js"}\n}'};
function detectLanguage(name){const ext=name.split('.').pop().toLowerCase();const m={js:'javascript',jsx:'javascript',ts:'typescript',tsx:'typescript',html:'html',css:'css',json:'json',py:'python',java:'java',c:'c',h:'c',cpp:'cpp',cc:'cpp',cs:'csharp',go:'go',rs:'rust',php:'php',rb:'ruby',swift:'swift',kt:'kotlin',dart:'dart',sql:'sql',sh:'shell',bash:'shell',md:'markdown',yaml:'yaml',yml:'yaml',xml:'xml',lua:'lua',pl:'perl',r:'r',ps1:'powershell',graphql:'graphql'};return m[ext]||'plaintext'}
function App(){
const [files,setFiles]=useState(()=>JSON.parse(localStorage.getItem('fluxide-files')||'null')||DEFAULT_FILES),[active,setActive]=useState('main.js'),[draft,setDraft]=useState(files['main.js']),[language,setLanguage]=useState('javascript'),[query,setQuery]=useState(''),[output,setOutput]=useState('Ready. Welcome to FluxIDE.'),[version]=useState('0.2.0'),[latest,setLatest]=useState(null),[theme,setTheme]=useState('dark'),[showPalette,setShowPalette]=useState(false),[showSettings,setShowSettings]=useState(false),[sidebar,setSidebar]=useState(true),[zoom,setZoom]=useState(14),[history,setHistory]=useState([]),[activePanel,setActivePanel]=useState('output');
useEffect(()=>localStorage.setItem('fluxide-files',JSON.stringify(files)),[files]);useEffect(()=>{setDraft(files[active]??'');setLanguage(detectLanguage(active))},[active]);useEffect(()=>{const k=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setShowPalette(v=>!v)}if(e.key==='Escape'){setShowPalette(false);setShowSettings(false)}};addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[draft,active,files]);
const visible=useMemo(()=>Object.keys(files).filter(f=>f.toLowerCase().includes(query.toLowerCase())),[files,query]);
function save(){setHistory(h=>[...h,{file:active,content:files[active],time:new Date().toLocaleTimeString()}].slice(-20));setFiles(v=>({...v,[active]:draft}));setOutput(`✓ Saved ${active}`)}
function newFile(){const n=prompt('New file name','untitled.js');if(!n||files[n])return;setFiles(v=>({...v,[n]:''}));setActive(n);setDraft('');setOutput(`Created ${n}`)}
function newProject(){if(!confirm('Create a new empty project?'))return;const n={'main.js':'console.log("Hello, FluxIDE!");','README.md':'# New FluxIDE Project\n'};setFiles(n);setActive('main.js');setDraft(n['main.js']);setOutput('New project created.')}
function remove(){if(!confirm(`Delete ${active}?`))return;const n={...files};delete n[active];const f=Object.keys(n)[0]||'main.js';if(!Object.keys(n).length)n[f]='';setFiles(n);setActive(f);setOutput(`Deleted ${active}`)}
function run(){setActivePanel('output');if(language==='javascript'){try{const logs=[],old=console.log;console.log=(...x)=>logs.push(x.join(' '));new Function(draft)();console.log=old;setOutput(logs.join('\n')||'Process finished with no console output.')}catch(e){setOutput('Runtime error: '+e.message)}}else setOutput(`${LANGUAGES.find(x=>x[0]===language)?.[1]} editing is supported. Native execution will arrive with the Electron runtime.`)}
function format(){if(language==='json'){try{setDraft(JSON.stringify(JSON.parse(draft),null,2));setOutput('✓ Formatted JSON')}catch(e){setOutput('Format error: '+e.message)}}else {setDraft(draft.split('\n').map(x=>x.trimEnd()).join('\n'));setOutput('✓ Basic formatting applied')}}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([draft],{type:'text/plain'}));a.download=active;a.click();setOutput(`Downloaded ${active}`)}
function upload(){const i=document.createElement('input');i.type='file';i.onchange=()=>{const f=i.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{setFiles(v=>({...v,[f.name]:String(r.result)}));setActive(f.name);setOutput(`Imported ${f.name}`)};r.readAsText(f)};i.click()}
function copy(){navigator.clipboard?.writeText(draft);setOutput('Copied file contents to clipboard.')}
async function updates(){setOutput('Checking update endpoint…');try{const r=await fetch(localStorage.getItem('fluxide-update-url')||'/update.json',{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();setLatest(d.version);setOutput(d.version!==version?`⬆ Update available: ${d.version}`:`✓ You're up to date (${version}).`)}catch(e){setOutput(`Update check unavailable. (${e.message})`)}}
function command(cmd){setShowPalette(false);if(cmd==='new')newFile();if(cmd==='project')newProject();if(cmd==='save')save();if(cmd==='run')run();if(cmd==='format')format();if(cmd==='download')download();if(cmd==='upload')upload();if(cmd==='updates')updates();if(cmd==='settings')setShowSettings(true)}
return <div className={'app '+theme}><header><button className="icon" onClick={()=>setSidebar(v=>!v)} title="Toggle sidebar"><PanelLeft/></button><div className="brand">FluxIDE <span>WEB</span></div><div className="actions"><button onClick={newProject}><FolderPlus/> New Project</button><button onClick={save}><Save/> Save</button><button onClick={run}><Play/> Run</button><button onClick={()=>setShowPalette(true)}><Command/> Command Palette</button><button onClick={updates}><RefreshCw/> Updates</button></div><div className="version">v{version}{latest&&latest!==version?<b> → v{latest}</b>:null}</div></header>
<div className="workspace">{sidebar&&<aside><div className="side-title"><Folder/> EXPLORER <button className="mini" onClick={newFile}><Plus/></button></div><div className="search"><Search/><input placeholder="Filter files" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="files">{visible.map(f=><button className={f===active?'file active':'file'} key={f} onClick={()=>setActive(f)}><FileCode2/>{f}{f===active&&draft!==files[f]?<i/>:null}</button>)}</div><div className="side-bottom"><button onClick={newFile}><FilePlus/> New File</button><button onClick={upload}><Upload/> Import File</button><button onClick={download}><Download/> Export Current File</button><button onClick={copy}><Copy/> Copy Contents</button><button onClick={remove}><Trash2/> Delete File</button><button onClick={()=>setActivePanel('source')}><GitBranch/> Source Control</button><button onClick={()=>setActivePanel('history')}><History/> Local History</button><button onClick={()=>setShowSettings(true)}><Settings/> Settings</button></div></aside>}
<main><div className="tabs"><div className="tab"><FileCode2/>{active}{draft!==files[active]?<strong>●</strong>:null}</div></div><div className="toolbar"><select value={language} onChange={e=>setLanguage(e.target.value)}>{LANGUAGES.map(([id,l])=><option key={id} value={id}>{l}</option>)}</select><button onClick={format}>Format</button><button onClick={()=>setZoom(z=>Math.min(24,z+1))}>A+</button><button onClick={()=>setZoom(z=>Math.max(10,z-1))}>A−</button><span>{draft===files[active]?'Saved':'Unsaved changes'} · {draft.length} chars</span></div><div className="editor"><Editor height="100%" theme={theme==='dark'?'vs-dark':'light'} language={language} value={draft} onChange={v=>setDraft(v??'')} options={{fontSize:zoom,minimap:{enabled:true},automaticLayout:true,tabSize:2,wordWrap:'on',bracketPairColorization:{enabled:true},smoothScrolling:true}}/></div><div className="bottom"><div className="bottom-tabs"><button className={activePanel==='output'?'selected':''} onClick={()=>setActivePanel('output')}><Terminal/> Output</button><button className={activePanel==='problems'?'selected':''} onClick={()=>setActivePanel('problems')}><CheckCircle2/> Problems</button><button className={activePanel==='source'?'selected':''} onClick={()=>setActivePanel('source')}><GitBranch/> Source Control</button><button className={activePanel==='history'?'selected':''} onClick={()=>setActivePanel('history')}><History/> History</button></div><pre>{activePanel==='output'?output:activePanel==='problems'?'No problems reported.':activePanel==='source'?'Working tree: local browser workspace. GitHub remote integration is planned.':history.length?history.map(x=>`${x.time}  ${x.file}`).join('\n'):'No local history yet.'}</pre></div></main></div>
<footer><span><GitBranch/> main</span><span>{Object.keys(files).length} files</span><span>{language}</span><span>Ctrl+S Save</span><span>Ctrl+K Command Palette</span><span className="grow"/><button className="icon" onClick={()=>setTheme(t=>t==='dark'?'light':'dark')}>{theme==='dark'?<Sun/>:<Moon/>}</button></footer>
{showPalette&&<div className="overlay" onClick={()=>setShowPalette(false)}><div className="palette" onClick={e=>e.stopPropagation()}><input autoFocus placeholder="Type a command…"/><button onClick={()=>command('new')}><FilePlus/> New File</button><button onClick={()=>command('project')}><FolderPlus/> New Project</button><button onClick={()=>command('save')}><Save/> Save</button><button onClick={()=>command('run')}><Play/> Run</button><button onClick={()=>command('format')}><Command/> Format Document</button><button onClick={()=>command('download')}><Download/> Export File</button><button onClick={()=>command('upload')}><Upload/> Import File</button><button onClick={()=>command('updates')}><RefreshCw/> Check for Updates</button><button onClick={()=>command('settings')}><Settings/> Settings</button></div></div>}
{showSettings&&<div className="overlay" onClick={()=>setShowSettings(false)}><div className="settings" onClick={e=>e.stopPropagation()}><h2>FluxIDE Settings</h2><label>Update endpoint<input defaultValue={localStorage.getItem('fluxide-update-url')||'/update.json'} onChange={e=>localStorage.setItem('fluxide-update-url',e.target.value)}/></label><label>Editor font size<input type="number" min="10" max="24" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><p>Workspace data is stored locally in your browser.</p><button onClick={()=>setShowSettings(false)}>Close</button></div></div>}
</div>}
createRoot(document.getElementById('root')).render(<App/>);