import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import Editor from '@monaco-editor/react';
import {Folder,FileCode2,GitBranch,Search,Play,Save,RefreshCw,Plus,Trash2,Terminal,CheckCircle2,Download,Upload,Copy,Command,Settings,FilePlus,FolderPlus,History,PanelLeft,Sun,Moon,Cloud,ChevronRight,ChevronDown,Braces,Eye,SplitSquareHorizontal,X,FileText} from 'lucide-react';
import './styles.css';
const LANGUAGES=[['javascript','JavaScript'],['typescript','TypeScript'],['html','HTML'],['css','CSS'],['json','JSON'],['python','Python'],['java','Java'],['c','C'],['cpp','C++'],['csharp','C#'],['go','Go'],['rust','Rust'],['php','PHP'],['ruby','Ruby'],['swift','Swift'],['kotlin','Kotlin'],['dart','Dart'],['sql','SQL'],['shell','Shell'],['markdown','Markdown'],['yaml','YAML'],['xml','XML'],['dockerfile','Dockerfile'],['graphql','GraphQL'],['lua','Lua'],['perl','Perl'],['r','R'],['powershell','PowerShell'],['plaintext','Plain Text']];
const DEFAULT_FILES={'main.js':'function hello() {\n  console.log("Hello from FluxIDE!");\n}\n\nhello();','README.md':'# FluxIDE\n\nA web-first developer workspace.\n\nCtrl+K opens the command palette.','package.json':'{\n  "name": "my-project",\n  "version": "1.0.0"\n}'};
function detectLanguage(n){const e=n.split('.').pop().toLowerCase();return ({js:'javascript',jsx:'javascript',ts:'typescript',tsx:'typescript',html:'html',css:'css',json:'json',py:'python',java:'java',c:'c',h:'c',cpp:'cpp',cc:'cpp',cs:'csharp',go:'go',rs:'rust',php:'php',rb:'ruby',swift:'swift',kt:'kotlin',dart:'dart',sql:'sql',sh:'shell',bash:'shell',md:'markdown',yaml:'yaml',yml:'yaml',xml:'xml',lua:'lua',pl:'perl',r:'r',ps1:'powershell',graphql:'graphql',dockerfile:'dockerfile'})[e]||'plaintext'}
function App(){
const [files,setFiles]=useState(()=>JSON.parse(localStorage.getItem('fluxide-files')||'null')||DEFAULT_FILES);
const [active,setActive]=useState('main.js');
const [draft,setDraft]=useState(files['main.js']);
const [language,setLanguage]=useState('javascript');
const [query,setQuery]=useState('');
const [output,setOutput]=useState('Ready. Welcome to FluxIDE.');
const [version]=useState('0.4.0');
const [latest,setLatest]=useState(null);
const [theme,setTheme]=useState(localStorage.getItem('fluxide-theme')||'dark');
const [palette,setPalette]=useState(false);
const [settings,setSettings]=useState(false);
const [sidebar,setSidebar]=useState(true);
const [zoom,setZoom]=useState(14);
const [history,setHistory]=useState([]);
const [panel,setPanel]=useState('output');
const [split,setSplit]=useState(false);
const [tabs,setTabs]=useState(['main.js']);
const [outline,setOutline]=useState(true);
const [terminal,setTerminal]=useState('');
useEffect(()=>localStorage.setItem('fluxide-files',JSON.stringify(files)),[files]);
useEffect(()=>{setDraft(files[active]??'');setLanguage(detectLanguage(active));if(!tabs.includes(active))setTabs(t=>[...t,active])},[active]);
useEffect(()=>localStorage.setItem('fluxide-theme',theme),[theme]);
useEffect(()=>{const k=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='p'){e.preventDefault();document.querySelector('.search input')?.focus()}if(e.key==='Escape'){setPalette(false);setSettings(false)}};addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[draft,active,files]);
const visible=useMemo(()=>Object.keys(files).filter(f=>f.toLowerCase().includes(query.toLowerCase())),[files,query]);
function save(){setHistory(h=>[...h,{file:active,time:new Date().toLocaleTimeString(),content:files[active]}].slice(-30));setFiles(v=>({...v,[active]:draft}));setOutput(`✓ Saved ${active}`)}
function newFile(){const n=prompt('New file name','untitled.js');if(!n||files[n])return;setFiles(v=>({...v,[n]:''}));setActive(n);setOutput(`Created ${n}`)}
function newProject(){if(!confirm('Create a new empty project?'))return;const n={'main.js':'console.log("Hello, FluxIDE!");','README.md':'# New FluxIDE Project\n'};setFiles(n);setTabs(['main.js']);setActive('main.js');setOutput('New project created.')}
function remove(){if(!confirm(`Delete ${active}?`))return;const n={...files};delete n[active];const f=Object.keys(n)[0]||'main.js';if(!Object.keys(n).length)n[f]='';setFiles(n);setTabs(t=>t.filter(x=>x!==active));setActive(f);setOutput(`Deleted ${active}`)}
function closeTab(f){const n=tabs.filter(x=>x!==f);setTabs(n);if(active===f&&n.length)setActive(n[n.length-1])}
function duplicate(){let n=active.replace(/(\.[^.]*)?$/,'-copy$1'),i=2;while(files[n])n=active.replace(/(\.[^.]*)?$/,'-copy'+i+++'$1');setFiles(v=>({...v,[n]:draft}));setActive(n)}
function run(){setPanel('output');if(language!=='javascript'){setOutput(`${language} editing is supported. Native execution arrives with Electron.`);return}try{const logs=[],old=console.log;console.log=(...x)=>logs.push(x.map(String).join(' '));new Function(draft)();console.log=old;setOutput(logs.join('\n')||'Process finished with no console output.')}catch(e){setOutput('Runtime error: '+e.message)}}
function format(){if(language==='json'){try{setDraft(JSON.stringify(JSON.parse(draft),null,2));setOutput('✓ Formatted JSON')}catch(e){setOutput('Format error: '+e.message)}}else setDraft(draft.split('\n').map(x=>x.trimEnd()).join('\n'))}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([draft],{type:'text/plain'}));a.download=active;a.click();setOutput(`Downloaded ${active}`)}
function upload(){const i=document.createElement('input');i.type='file';i.multiple=true;i.onchange=()=>Array.from(i.files||[]).forEach(f=>{const r=new FileReader();r.onload=()=>{setFiles(v=>({...v,[f.name]:String(r.result)}));setActive(f.name)};r.readAsText(f)});i.click()}
function copy(){navigator.clipboard?.writeText(draft);setOutput('Copied contents to clipboard.')}
async function updates(){setOutput('Checking update endpoint…');try{const r=await fetch('/update.json',{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();setLatest(d.version);setOutput(d.version!==version?`⬆ Update available: ${d.version}`:`✓ You are up to date (${version}).`)}catch(e){setOutput(`Update check unavailable. (${e.message})`)} }
function command(c){setPalette(false);({new:newFile,project:newProject,save,run,format,download,upload,updates,settings:()=>setSettings(true),terminal:()=>setPanel('terminal'),problems:()=>setPanel('problems'),split:()=>setSplit(v=>!v),outline:()=>setOutline(v=>!v)})[c]?.()}
const lines=draft.split('\n');
return <div className={'app '+theme}><header><button className="icon" onClick={()=>setSidebar(v=>!v)}><PanelLeft/></button><div className="brand">FluxIDE <span>WEB</span></div><div className="actions"><button onClick={newProject}><FolderPlus/> New Project</button><button onClick={save}><Save/> Save</button><button onClick={run}><Play/> Run</button><button onClick={()=>setPalette(true)}><Command/> Commands</button><button onClick={()=>setPanel('source')}><GitBranch/> Source</button><button onClick={updates}><RefreshCw/> Updates</button></div><div className="version">v{version}{latest&&latest!==version?<b> → v{latest}</b>:null}</div></header>
<div className="workspace">{sidebar&&<aside><div className="side-title"><Folder/> EXPLORER <button className="mini" onClick={newFile}><Plus/></button></div><div className="search"><Search/><input placeholder="Search files (Ctrl+P)" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="files">{visible.map(f=><button className={f===active?'file active':'file'} key={f} onClick={()=>setActive(f)}><FileCode2/>{f}{f===active&&draft!==files[f]?<i/>:null}</button>)}</div><div className="outline"><div onClick={()=>setOutline(v=>!v)}>{outline?<ChevronDown/>:<ChevronRight/>}<Braces/> OUTLINE</div>{outline&&<small>{lines.filter(x=>/function|class|const|let|var/.test(x)).slice(0,10).map((x,i)=><span key={i}>{x.trim().slice(0,45)}</span>)}</small>}</div><div className="side-bottom"><button onClick={newFile}><FilePlus/> New File</button><button onClick={upload}><Upload/> Import Files</button><button onClick={download}><Download/> Export File</button><button onClick={copy}><Copy/> Copy Contents</button><button onClick={duplicate}><Copy/> Duplicate</button><button onClick={remove}><Trash2/> Delete</button><button onClick={()=>setPanel('source')}><GitBranch/> Source Control</button><button onClick={()=>setPanel('history')}><History/> Local History</button><button onClick={()=>setSettings(true)}><Settings/> Settings</button></div></aside>}
<main><div className="tabs">{tabs.map(f=><div className={'tab '+(f===active?'tab-active':'')} key={f} onClick={()=>setActive(f)}><FileCode2/>{f}{f===active&&draft!==files[f]?<strong>●</strong>:null}<button onClick={e=>{e.stopPropagation();closeTab(f)}}><X/></button></div>)}<button className="newtab" onClick={newFile}><Plus/></button></div><div className="toolbar"><select value={language} onChange={e=>setLanguage(e.target.value)}>{LANGUAGES.map(([id,l])=><option key={id} value={id}>{l}</option>)}</select><button onClick={format}>Format</button><button onClick={()=>setZoom(z=>Math.min(24,z+1))}>A+</button><button onClick={()=>setZoom(z=>Math.max(10,z-1))}>A−</button><button onClick={()=>setSplit(v=>!v)}><SplitSquareHorizontal/></button><span>{draft===files[active]?'Saved':'Unsaved changes'} · {draft.length} chars · Ln {lines.length}</span></div><div className={split?'editors split':'editors'}><div className="editor"><Editor height="100%" theme={theme==='dark'?'vs-dark':'light'} language={language} value={draft} onChange={v=>setDraft(v??'')} options={{fontSize:zoom,minimap:{enabled:true},automaticLayout:true,tabSize:2,wordWrap:'on',bracketPairColorization:{enabled:true},smoothScrolling:true,stickyScroll:{enabled:true},codeLens:true,renderWhitespace:'selection',quickSuggestions:true}}/></div>{split&&<div className="editor second"><Editor height="100%" theme={theme==='dark'?'vs-dark':'light'} language={language} value={draft} options={{fontSize:zoom,minimap:{enabled:false},automaticLayout:true,readOnly:true,wordWrap:'on'}}/></div>}</div><div className="bottom"><div className="bottom-tabs">{[['output',Terminal,'Output'],['problems',CheckCircle2,'Problems'],['source',GitBranch,'Source Control'],['history',History,'History'],['terminal',Command,'Terminal']].map(([id,I,n])=><button className={panel===id?'selected':''} key={id} onClick={()=>setPanel(id)}><I/> {n}</button>)}</div>{panel==='terminal'?<div className="terminal"><span>$</span><input autoFocus value={terminal} onChange={e=>setTerminal(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){setOutput(`$ ${terminal}\nBrowser terminal: execution requires Electron.`);setPanel('output');setTerminal('')}}}/></div>:<pre>{panel==='output'?output:panel==='problems'?'✓ No problems reported.':panel==='source'?'Browser source control workspace ready. Native Git requires Electron or a backend.':history.length?history.map(x=>`${x.time}  ${x.file}`).join('\n`'):'No local history yet.'}</pre>}</div></main></div>
<footer><span><GitBranch/> main</span><span>{Object.keys(files).length} files</span><span>{language}</span><span>Ln {lines.length}</span><span>Spaces: 2</span><span>UTF-8</span><span className="grow"/><button className="icon" onClick={()=>setTheme(t=>t==='dark'?'light':'dark')}>{theme==='dark'?<Sun/>:<Moon/>}</button></footer>
{palette&&<div className="overlay" onClick={()=>setPalette(false)}><div className="palette" onClick={e=>e.stopPropagation()}><input autoFocus placeholder="Type a command…"/><button onClick={()=>command('new')}><FilePlus/> New File</button><button onClick={()=>command('project')}><FolderPlus/> New Project</button><button onClick={()=>command('save')}><Save/> Save</button><button onClick={()=>command('run')}><Play/> Run</button><button onClick={()=>command('format')}><Braces/> Format Document</button><button onClick={()=>command('split')}><SplitSquareHorizontal/> Split Editor</button><button onClick={()=>command('terminal')}><Terminal/> Terminal</button><button onClick={()=>command('problems')}><CheckCircle2/> Problems</button><button onClick={()=>command('outline')}><Eye/> Toggle Outline</button><button onClick={()=>command('download')}><Download/> Export</button><button onClick={()=>command('upload')}><Upload/> Import</button><button onClick={()=>command('updates')}><RefreshCw/> Check Updates</button><button onClick={()=>command('settings')}><Settings/> Settings</button></div></div>}
{settings&&<div className="overlay" onClick={()=>setSettings(false)}><div className="settings" onClick={e=>e.stopPropagation()}><h2>FluxIDE Settings</h2><label>Editor font size<input type="number" min="10" max="24" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><p>Browser workspace data is stored locally. Native folders, terminal processes, debugging and real Git are reserved for the Electron/backend phase.</p><button onClick={()=>setSettings(false)}>Close</button></div></div>}
</div>}
createRoot(document.getElementById('root')).render(<App/>);