import * as monaco from 'monaco-editor';

const COMPILER_API = 'https://codecompiler.forgesparse.com/api/run';
const COMPILER_LANGUAGES = new Set(['typescript','python','java','c','cpp','csharp','go','rust','php','ruby','kotlin','dart','sql','shell','lua','perl','r','powershell']);
const API_LANGUAGE = {typescript:'typescript',python:'python',java:'java',c:'c',cpp:'cpp',csharp:'csharp',go:'go',rust:'rust',php:'php',ruby:'ruby',kotlin:'kotlin',dart:'dart',sql:'sqlite',shell:'bash',lua:'lua',perl:'perl',r:'r',powershell:'powershell'};
const EXTENSION = {typescript:'ts',python:'py',java:'java',c:'c',cpp:'cpp',csharp:'cs',go:'go',rust:'rs',php:'php',ruby:'rb',kotlin:'kt',dart:'dart',sql:'sql',shell:'sh',lua:'lua',perl:'pl',r:'r',powershell:'ps1'};
function activeFileName(){const tab=document.querySelector('.tab-active');return tab?.textContent?.replace('×','').replace('●','').trim()||'main.txt'}
function activeModel(){const models=monaco.editor.getModels().filter(m=>!m.isDisposed());if(!models.length)return null;const lang=document.querySelector('main .toolbar select')?.value;const matching=models.filter(m=>m.getLanguageId()===lang);return matching[matching.length-1]||models[models.length-1]}
function output(text){const value=String(text??'');const outputButton=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='Output');if(outputButton)outputButton.click();const paint=()=>{const pre=document.querySelector('.bottom pre');if(pre)pre.textContent=value};requestAnimationFrame(paint);setTimeout(paint,30);setTimeout(paint,120)}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function localRun(language,source,filename){
  if(language==='flux'){const lines=[],variables={};const print=/\b(?:print|say)\s*\(([^)]*)\)/g;let match;for(const declaration of source.matchAll(/\b(?:let|make|const|var|fixed)\s+([A-Za-z_]\w*)\s*=\s*["']([^"']*)["']/g))variables[declaration[1]]=declaration[2];while((match=print.exec(source))){let value=match[1].trim();value=value.replace(/^(["'`])([\s\S]*)\1$/,'$2');value=value.replace(/\b([A-Za-z_][A-Za-z0-9_]*)\b/g,n=>Object.prototype.hasOwnProperty.call(variables,n)?variables[n]:n);lines.push(value)}return lines.length?lines.join('\n'):'✓ Flux parsed successfully.\n\nNo print()/say() output was produced.'}
  if(language==='json'){try{return `✓ Valid JSON\n\n${JSON.stringify(JSON.parse(source),null,2)}`}catch(e){return `JSON error: ${e.message}`}}
  if(language==='markdown'){const html=source.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/^[-*] (.*)$/gm,'<li>$1</li>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>').replace(/\n\n+/g,'</p><p>').replace(/\n/g,'<br>');const preview=window.open('','_blank');if(!preview)return'Markdown preview was blocked by the browser.';preview.document.write(`<!doctype html><html><head><title>${escapeHtml(filename)}</title><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;max-width:900px;margin:50px auto;padding:0 24px;line-height:1.7;color:#222}h1,h2,h3{line-height:1.2}li{margin:6px 0}</style></head><body><p>${html}</p></body></html>`);preview.document.close();return`✓ Markdown preview opened for ${filename}.`}
  if(language==='xml'){const doc=new DOMParser().parseFromString(source,'application/xml');const error=doc.querySelector('parsererror');return error?`XML error:\n${error.textContent}`:`✓ Valid XML\n\nRoot: <${doc.documentElement?.tagName||'none'}>`}
  if(language==='yaml'){const lines=source.split(/\r?\n/);const bad=lines.findIndex(l=>l.trim()&&!l.trim().startsWith('#')&&!/^(?:- |[\w.-]+\s*:|[\w.-]+\s*$)/.test(l.trim()));return bad>=0?`YAML validation error near line ${bad+1}: ${lines[bad]}`:`✓ YAML structure looks valid.\n\n${lines.filter(Boolean).length} non-empty lines.`}
  if(language==='dockerfile'){const instructions=source.split(/\r?\n/).filter(l=>l.trim()&&!l.trim().startsWith('#'));const valid=instructions.every(l=>/^[A-Z][A-Z0-9_-]*(?:\s|$)/.test(l.trim()));return valid?`✓ Dockerfile looks valid.\n\n${instructions.length} instruction(s) found.`:'Dockerfile validation error: every instruction must start with a Docker directive such as FROM, RUN, COPY, CMD or ENTRYPOINT.'}
  if(language==='graphql'){const opens=(source.match(/\{/g)||[]).length,closes=(source.match(/\}/g)||[]).length,hasOperation=/\b(?:query|mutation|subscription|fragment)\b/.test(source);if(opens!==closes)return`GraphQL syntax error: ${opens} opening brace(s) and ${closes} closing brace(s).`;return hasOperation?'✓ GraphQL document structure looks valid.':'✓ GraphQL selection set parsed. Add a query, mutation, subscription or fragment for a complete operation.'}
  if(language==='css'){const opens=(source.match(/\{/g)||[]).length,closes=(source.match(/\}/g)||[]).length;return opens===closes?`✓ CSS parsed.\n\n${opens} rule block(s). Use Live Preview to see the stylesheet in a page.`:`CSS syntax error: ${opens} opening brace(s), ${closes} closing brace(s).`}
  if(language==='plaintext')return source||'Plain Text file is empty.';
  return null;
}
async function remoteRun(language,source,filename){const apiLanguage=API_LANGUAGE[language];if(!apiLanguage)return null;output(`Running ${language}…\n\nSending code to the sandbox compiler…`);try{const response=await fetch(COMPILER_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language:apiLanguage,files:[{name:filename||`main.${EXTENSION[language]||'txt'}`,content:source}]})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`HTTP ${response.status}`);if(data.error)throw new Error(data.error);const stdout=data.stdout||'',stderr=data.stderr||'',combined=data.output||stdout||stderr||'(program finished with no output)';output(`${combined}${stderr&&!combined.includes(stderr)?`\n\n[stderr]\n${stderr}`:''}`)}catch(error){output(`Could not run ${language}: ${error.message}\n\nThe compiler service is an external sandbox. If it is unavailable or blocks browser requests, FluxIDE will keep the editor working normally.`)}}
function isSwiftUI(source){return /(^|\n)\s*(import\s+(SwiftUI|UIKit|AppKit)|@main\b|struct\s+\w+\s*:\s*(View|App)|UIViewController\b)/m.test(source)}
async function handleRun(){const model=activeModel();const language=document.querySelector('main .toolbar select')?.value||model?.getLanguageId()||'plaintext';const source=model?.getValue()??'';const filename=activeFileName();if(language==='html'||(language==='swift'&&isSwiftUI(source)))return;const local=localRun(language,source,filename);if(local!==null){output(local);return}if(COMPILER_LANGUAGES.has(language)){await remoteRun(language,source,filename);return}output(`✓ ${language} file loaded.\n\nThis file type is a data/configuration format rather than an executable program.`)}
function install(){const attach=()=>{const runButton=[...document.querySelectorAll('header .actions button')].find(b=>b.textContent.trim()==='Run');if(!runButton||runButton.dataset.universalRunnerInstalled)return!!runButton;runButton.dataset.universalRunnerInstalled='1';runButton.addEventListener('click',()=>{setTimeout(()=>{void handleRun()},0)});return true};if(attach())return;const observer=new MutationObserver(()=>{if(attach())observer.disconnect()});observer.observe(document.documentElement,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
